name: prayer_alarm_app
description: Aplikasi alarm jadwal sholat dengan deteksi lokasi otomatis
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Background service
  flutter_background_service: ^5.0.5

  # Location
  geolocator: ^12.0.0

  # HTTP
  http: ^1.2.0

  # Alarm & Notifikasi
  flutter_local_notifications: ^17.2.2
  android_alarm_manager_plus: ^4.0.1

  # Audio adzan
  just_audio: ^0.9.39
  audio_session: ^0.1.21

  # Homescreen widget
  home_widget: ^0.6.0

  # Timezone
  timezone: ^0.9.4

  # Storage
  shared_preferences: ^2.2.3

  # Permission
  permission_handler: ^11.3.1

  # UI
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/animations/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
